plugins:
  - react

parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    arrowFunctions: true
    binaryLiterals: true
    blockBindings: true
    classes: true
    defaultParams: false
    destructuring: true
    experimentalObjectRestSpread: true
    forOf: false
    generators: false
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: false
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    octalLiterals: false
    regexUFlag: false
    regexYFlag: false
    restParams: false
    spread: false
    superInFunctions: false
    templateStrings: true
    unicodeCodePointEscapes: false
    globalReturn: false
    jsx: true
    # End ecmaFeatures as of eslint 0.23.0 [2015-06-15]

env:
  browser: true
  node: true
  es6: true
  mocha: true

globals:
  __DEV__: true,
  __PROD__: true,
  __TEST__: true,
  __COVERAGE__: true,
  PNL_API_BASE_URL: ""

rules:
  # Possible Errors
  comma-dangle: [2, 'never']
  no-console: 1
  no-control-regex: 2
  no-debugger: 1
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty-character-class: 2
  no-empty: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 0
  no-extra-parens: 0
  no-extra-semi: 2
  no-func-assign: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-regex-spaces: 2
  no-sparse-arrays: 2
  no-unreachable: 2
  use-isnan: 2
  valid-jsdoc: 0
  valid-typeof: 2
  # End Possible Errors as of eslint 0.23.0 [2015-06-15]

  # Best Practices
  accessor-pairs: 2
  block-scoped-var: 0
  complexity: 0
  consistent-return: 2
  curly: 2
  default-case: 0
  dot-notation: 2
  dot-location: 0
  eqeqeq: 2
  no-alert: 2
  no-caller: 2
  no-div-regex: 2
  no-else-return: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 0
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implied-eval: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-new: 2
  no-octal-escape: 2
  no-octal: 2
  no-param-reassign: 2
  no-proto: 2
  no-redeclare: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 1
  no-unused-expressions: [2, { allowShortCircuit: true }]
  no-void: 2
  no-warning-comments: 0
  no-with: 2
  radix: 2
  vars-on-top: 0
  # End Best Practices as of eslint 0.23.0 [2015-06-15]

  # Variables
  no-delete-var: 2
  no-label-var: 2
  no-shadow-restricted-names: 2
  no-shadow: 2
  no-undef-init: 2
  no-undef: 2
  no-unused-vars: 2
  no-use-before-define: [2, 'nofunc']
  # End Variables as of eslint 0.23.0 [2015-06-15]

  # Stylistic Issues
  brace-style: 0
  camelcase: 1
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, 'last']
  computed-property-spacing: [2, 'never']
  consistent-this: [2, 'self']
  eol-last: 0
  func-names: 0
  func-style: [2, 'declaration', { allowArrowFunctions: true }]
  indent: [2, 2, { SwitchCase: 1 }]
  lines-around-comment: 0
  linebreak-style: [2, 'unix']
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  max-len: [2, { code: 120, ignoreComments: true, ignoreTrailingComments: true } ]
  max-nested-callbacks: 0
  new-cap: 0
  new-parens: 2
  newline-after-var: 0
  no-array-constructor: 2
  no-inline-comments: 0
  no-lonely-if: 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines: 2
  no-nested-ternary: 2
  no-new-object: 2
  no-spaced-func: 2
  no-ternary: 0
  no-trailing-spaces: 2
  no-underscore-dangle: 0
  no-unneeded-ternary: 2
  one-var: 0
  padded-blocks: [2, 'never']
  quote-props: 0
  quotes: [2, 'single', 'avoid-escape']
  semi-spacing: [2, {before: false, after: true}]
  semi: [2, 'always']
  sort-vars: 0
  keyword-spacing: 2
  space-before-blocks: [2, 'always']
  space-before-function-paren: [2, 'never']
  object-curly-spacing: [2, 'always']
  space-in-parens: [2, 'never']
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: [2, 'always']
  wrap-regex: 0
  # End Stylistic Issues as of eslint 0.23.0 [2015-06-15]

  # es6
  no-var: 2
  prefer-const: 2
  # End es6 as of eslint 0.23.0 [2015-06-15]

  # eslint-plugin-react
  react/display-name: 0
  react/jsx-no-undef: 2
  react/jsx-sort-props: 0
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 2
  react/no-multi-comp: 0
  react/no-unknown-property: 2
  react/prop-types: 1
  react/react-in-jsx-scope: 2
  react/self-closing-comp: 2
  react/sort-comp: 0
  react/sort-prop-types: 0
  react/jsx-wrap-multilines: 2
  # End eslint-plugin-react as of eslint-plugin-react 2.3.0 [2015-05-14]

# vi: ft=yaml
